## NUMPY : Package for multidimensional array

### Vector(1 d)

### Matrix (2d or 1d)

In [1]:
import numpy as np

In [2]:
list = [3,4,7]

In [3]:
np.array(list)

array([3, 4, 7])

In [4]:
arr=np.array([2,5,8])
arr

array([2, 5, 8])

In [5]:
list_of_lists = ([1,2,3],[2,5,8],[9,5,1])
np.array(list_of_lists)

array([[1, 2, 3],
       [2, 5, 8],
       [9, 5, 1]])

In [6]:
np.arange(2,26)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25])

In [7]:
np.arange(2,26,7)

array([ 2,  9, 16, 23])

In [8]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(7,dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(7,dtype=int)

array([1, 1, 1, 1, 1, 1, 1])

In [13]:
np.linspace(0,26,7)

array([ 0.        ,  4.33333333,  8.66666667, 13.        , 17.33333333,
       21.66666667, 26.        ])

In [14]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [15]:
matrix =np.empty((5,5),dtype=int)
matrix

array([[ 321069176,        495,         50,          0,          0],
       [         0,          0,          0,          0,          0],
       [1852990827, 1663986789,  895562595,  758341989,  842228790],
       [ 926430253, 1664626018,  908944486,  825505078,  892625201],
       [ 775173425, 1952543859, 1600484213, 1970496882,  862155884]])

In [19]:
matrix =np.full((5,5),fill_value=7)
matrix

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.eye(7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [24]:
np.random.rand(2,3)

array([[0.30223355, 0.28089906, 0.51545491],
       [0.8019886 , 0.24895489, 0.78456716]])

In [25]:
np.random.randn(2,3)

array([[-0.66262443, -0.51067656, -0.40660919],
       [ 0.87452328, -0.24693023, -2.34786037]])

In [26]:
np.random.rand(2,5)

array([[0.27544241, 0.13632388, 0.23482067, 0.9528271 , 0.82082865],
       [0.89461332, 0.00299943, 0.05161516, 0.90032736, 0.96302238]])

In [27]:
np.random.randint(0,10,15)

array([1, 7, 3, 5, 7, 5, 9, 5, 6, 7, 0, 3, 9, 5, 0])

In [28]:
sample_array=np.arange(3,30)
sample_array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
rand_array=np.random.randint(0,10,5)
rand_array

array([8, 8, 0, 8, 0])

In [33]:
sample_array.min()

3

In [34]:
sample_array.max()

29

In [35]:
sample_array.argmax()

26

In [36]:
rand_array.min()

0

In [37]:
rand_array.max()

8

In [40]:
sample_array.dtype

dtype('int32')

In [41]:
sample_array[1]=100
sample_array

array([  3, 100,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29])

In [43]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [44]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [45]:
subset_sample_array = sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

## Two dimensional array

In [46]:
sample_matrix=np.array(([2,5,6,8],[7,6,1,9,],[4,6,9,3],[2,4,5,8]))
sample_matrix

array([[2, 5, 6, 8],
       [7, 6, 1, 9],
       [4, 6, 9, 3],
       [2, 4, 5, 8]])

In [47]:
sample_matrix[2][2]

9

In [48]:
sample_matrix[1][2]

1

In [49]:
sample_matrix[:,2]

array([6, 1, 9, 5])

In [50]:
sample_matrix[1,1]

6

In [51]:
sample_matrix[1:3,2:4]

array([[1, 9],
       [9, 3]])

In [52]:
sample_matrix[2]

array([4, 6, 9, 3])

In [57]:
sample_array = np.arange(1,21)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [59]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [60]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [61]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [62]:
np.max(sample_array)

20

In [63]:
np.min(sample_array)

1

In [64]:
np.argmax(sample_array)

19

In [65]:
np.argmin(sample_array)

0

In [66]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [67]:
np.std(sample_array)

5.766281297335398

In [68]:
np.var(sample_array)

33.25

In [69]:
np.mean(sample_array)

10.5

In [70]:
array = np.random.randn(3,4)      ## normal distribution
array

array([[ 1.41463976, -0.29258787, -1.27294496, -0.18632254],
       [-0.04232249,  0.43198928, -1.11133587,  0.41767353],
       [ 1.05285347, -1.248396  , -0.71760536,  1.10493522]])

In [71]:
np.round(array,decimals=3)

array([[ 1.415, -0.293, -1.273, -0.186],
       [-0.042,  0.432, -1.111,  0.418],
       [ 1.053, -1.248, -0.718,  1.105]])

In [72]:
sports = np.array(["basketball","golf","volleyball","throwball"])
sports

array(['basketball', 'golf', 'volleyball', 'throwball'], dtype='<U10')

In [ ]:
## create a null vector of size 10
## create a null vector of size 10 but the 5th value should be 1
## create a vector ranging from 10 to 65

In [6]:
import numpy as np
import pandas as pd

In [7]:
labels=['w','x','y','z']
list=[10,20,30,40]
array=np.array([10,20,30,40])
dict={'w':10,'x':20,'y':30,'z':40}

In [8]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [10]:
pd.Series(array,labels)

w    10
x    20
y    30
z    40
dtype: int32

In [11]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64